version: 2

jobs:

  test-coverage:

    docker:
      - image: circleci/node:10.12.0-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"

    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: "Add Greenkeeper"
          command: yarn global add greenkeeper-lockfile@1

      - run:
          name: "Install Dependencies"
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: "Start Ganache"
          command: yarn start-ganache
          background: true

      - run:
          name: "Wait for Ganache"
          command: dockerize -wait tcp://localhost:8545 -timeout 1m

      - run:
          name: "Deploy Contracts"
          command: yarn deploy-contracts

      - run:
          name: "Start Trufflepig"
          command: yarn start-trufflepig
          background: true

      - run:
          name: "Colony Setup"
          command: yarn colony-setup

      - run:
          name: "Test Packages"
          command: |
            $HOME/.config/yarn/global/node_modules/.bin/greenkeeper-lockfile-update
            yarn test
            $HOME/.config/yarn/global/node_modules/.bin/greenkeeper-lockfile-upload

workflows:

  version: 2

  commit:
    jobs:
      - test-coverage

  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - test-coverage
