version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: "Add Greenkeeper"
          command: yarn global add greenkeeper-lockfile@1

      - run:
          name: "Install Dependencies"
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: "Start Ganache"
          command: yarn run start-ganache
          background: true

      - run:
          name: "Deploy Contracts"
          command: yarn run deploy-contracts

      - run:
          name: "Start Trufflepig"
          command: scripts/ci_trufflepig.js
          background: true

      - run:
          name: "Run Tests"
          command: |
            $HOME/.config/yarn/global/node_modules/.bin/greenkeeper-lockfile-update
            yarn run test
            $HOME/.config/yarn/global/node_modules/.bin/greenkeeper-lockfile-upload
